import type { ReactNode } from "react";
import type { AnalyticsEventType, ExperienceModuleEventType } from "../../../shared/analytics/contracts";

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };

export type ExperienceSlot = "primary" | "secondary";
export type ExperienceAccessMode = "public" | "trial" | "authenticated";
export type ExperienceStatus = "published" | "unavailable" | "retired";

/**
 * An Experience is an installed/configured instance of a module, not the module
 * implementation itself. Organization configuration can replace the default
 * instance without changing the host contract.
 */
export interface Experience {
  id: string;
  organizationId: string | null;
  moduleId: string;
  moduleVersion: string;
  slot: ExperienceSlot;
  status: ExperienceStatus;
  configurationVersion: string;
  configuration: JsonObject;
}

export interface ExperienceCapability {
  key: string;
  label: string;
  description: string;
  availability: ExperienceAccessMode[];
  requiresEntitlement?: boolean;
  quotaUnit?: string;
  upgradeContext?: string;
}

/** Customer access generated by a trusted backend. Staff roles are separate. */
export interface Entitlement {
  id: string;
  organizationId: string;
  customerId: string;
  experienceId: string;
  capabilityKey: string;
  status: "active" | "expired" | "revoked";
  kind: "grant" | "allowance";
  source: "offer" | "subscription" | "organization" | "trial";
  verifiedAt: string;
  expiresAt?: string;
  remaining?: number;
  resetAt?: string;
}

/**
 * Presentation-only access input. A browser may render from this snapshot, but
 * a protected backend operation must independently re-authorize scope,
 * entitlement validity, and quota. Track B never derives this from checkout UI.
 */
export interface EntitlementPresentationSnapshot {
  trust: "server-derived";
  fetchedAt: string;
  organizationId: string;
  customerId: string;
  entitlements: Entitlement[];
}

export type EntitlementSnapshotResult =
  | { status: "ready"; snapshot: EntitlementPresentationSnapshot }
  | { status: "unavailable"; reason: string };

export type CapabilityDenialReason =
  | "capability-undeclared"
  | "mode-not-supported"
  | "authentication-required"
  | "trusted-entitlement-unavailable"
  | "entitlement-not-granted"
  | "entitlement-expired"
  | "quota-exhausted"
  | "scope-mismatch";

export interface ExperienceCapabilityDecision {
  allowed: boolean;
  capabilityKey: string;
  reason: "mode-grant" | "entitlement-grant" | CapabilityDenialReason;
  explanation: string;
  entitlement?: Entitlement;
}

export interface ExperienceRouteDefinition {
  /** Empty string represents the module's index route. */
  path: string;
  label: string;
  access: ExperienceAccessMode[];
  capability?: string;
}

export interface ExperienceNavigationItem extends ExperienceRouteDefinition {
  description?: string;
}

export interface ExperienceConfigurationField {
  type: "string" | "number" | "boolean" | "array" | "object";
  label: string;
  description?: string;
  required?: boolean;
}

export interface ExperienceEventPayloadField {
  type: "string" | "number" | "boolean";
  required?: boolean;
  maxLength?: number;
  integer?: boolean;
  min?: number;
  max?: number;
  allowedValues?: readonly (string | number | boolean)[];
}

/**
 * Developer-owned declaration for a module event. This is configuration data,
 * not executable validation code. The host applies the bounded validator in
 * `events.ts` before the event reaches Track F's lifecycle submission boundary.
 */
export interface ExperienceEventDefinition {
  name: ExperienceModuleEventType;
  description: string;
  source: "browser" | "domain_action";
  schemaVersion: 1;
  payloadSchema: Record<string, ExperienceEventPayloadField>;
  /** Per-event cap; may only narrow Track F's canonical global payload cap. */
  maxPayloadBytes?: number;
  requiresServerValidation?: boolean;
}

export interface ExperienceProfileRequirement {
  field: string;
  purpose: string;
  required: boolean;
  sensitivity: "standard" | "sensitive";
}

/**
 * Modules describe only the requirement. Track C owns conversion into its
 * namespaced OnboardingExtension, ordering, validation, persistence, and
 * completion. Track B never writes onboarding state directly.
 */
export interface ExperienceOnboardingRequirement {
  id: string;
  label: string;
  completion: string;
}

export interface ExperienceActivityDefinition {
  meaningfulEvent: ExperienceModuleEventType;
  description: string;
  pageViewCountsAsActivity: false;
  activation: {
    /** Browser/domain event that indicates a candidate first meaningful use. */
    moduleEvent: ExperienceModuleEventType;
    /** Stable domain milestone key emitted globally only after trusted validation. */
    milestoneKey: string;
    verification: "trusted-domain-action";
  };
}

export interface ExperienceDataContract {
  scope: "organization-customer" | "organization" | "customer" | "session-only";
  retention: string;
  export: string;
  migration: string;
}

export interface ExperienceCompatibility {
  hostContract: string;
  hostVersion: string;
  unavailableBehavior: string;
}

export interface ExperienceModuleManifest {
  id: string;
  version: string;
  contractVersion: string;
  name: string;
  description: string;
  icon: string;
  routes: ExperienceRouteDefinition[];
  navigation: ExperienceNavigationItem[];
  configurationSchema: Record<string, ExperienceConfigurationField>;
  defaults: JsonObject;
  capabilities: ExperienceCapability[];
  eventDefinitions: ExperienceEventDefinition[];
  profileRequirements: ExperienceProfileRequirement[];
  onboardingRequirements: ExperienceOnboardingRequirement[];
  activityDefinition: ExperienceActivityDefinition;
  dataContract: ExperienceDataContract;
  compatibility: ExperienceCompatibility;
}

export interface ExperienceImageAsset {
  id: string;
  kind: "image";
  provider: "pexels" | "unsplash" | "uploaded" | "direct";
  title: string;
  deliveryUrl: string;
  sourceUrl: string;
  alt: string;
  creator?: string;
  licenseUrl?: string;
}

export interface ExperienceVideoAsset {
  id: string;
  kind: "video";
  provider: "youtube" | "vimeo" | "direct";
  title: string;
  sourceUrl: string;
  deliveryUrl?: string;
  mimeType?: "video/mp4" | "video/webm";
  posterUrl?: string;
  captionsUrl?: string;
  transcriptUrl?: string;
}

export type ExperienceMediaAsset = ExperienceImageAsset | ExperienceVideoAsset;

/** Browser-observed Experience signal. Tenant/customer values are hints only. */
export interface ExperienceLifecycleEvent {
  eventId: string;
  eventType: AnalyticsEventType;
  occurredAt: string;
  source: "experience-browser";
  trust: "browser-observed";
  schemaVersion: 1;
  organizationId?: string;
  identityId?: string;
  customerId?: string;
  experienceId: string;
  moduleId: string;
  moduleVersion: string;
  idempotencyKey?: string;
  properties: JsonObject;
}

/** Track A integration: canonical public organization/tenant resolution. */
export interface ExperienceOrganizationScopeRequest {
  accessMode: ExperienceAccessMode;
  authenticatedOrganizationId?: string;
}

export interface ExperienceOrganizationSource {
  resolveOrganizationId(request: ExperienceOrganizationScopeRequest): string | null;
}

/** Track A integration: published organization Experience/configuration. */
export interface ExperienceDefinitionRequest {
  organizationId?: string;
  slot: ExperienceSlot;
  moduleId: string;
  moduleVersion: string;
}

export interface ExperienceDefinitionSource {
  loadPublishedExperience(request: ExperienceDefinitionRequest): Promise<Experience | null>;
}

/**
 * Track C integration. Track C returns the stable Nurture Customer/Profile ID
 * even when organization context is supplied. The organization value remains
 * context only; tenant authority is re-bound by Track E and re-checked by the
 * entitlement/protected-operation boundary.
 */
export interface ExperienceCustomerRequest {
  organizationId?: string;
  identityId: string;
}

export type ExperienceCustomerResult =
  | { status: "ready"; customerId: string }
  | { status: "unavailable"; reason: string };

export interface ExperienceCustomerSource {
  resolveCustomer(request: ExperienceCustomerRequest): Promise<ExperienceCustomerResult>;
}

/** Tracks D/E integration: browser receives only a server-derived presentation snapshot. */
export interface ExperienceEntitlementRequest {
  organizationId?: string;
  identityId?: string;
  customerId?: string;
  experienceId: string;
  moduleId: string;
}

export interface ExperienceEntitlementSource {
  loadPresentationSnapshot(request: ExperienceEntitlementRequest): Promise<EntitlementSnapshotResult>;
}

/** Track F/lifecycle integration: browser events are signals, never authority. */
export interface ExperienceEventSink {
  submit(event: ExperienceLifecycleEvent): void | Promise<void>;
}

/**
 * Browser-side request for a trusted milestone. Organization/customer/identity
 * authority is deliberately absent; the server adapter must derive identity
 * from authenticated request state and re-bind the organization through Track E.
 */
export interface ExperienceMilestoneRequest {
  organizationId: string;
  experienceId: string;
  moduleId: string;
  moduleVersion: string;
  milestoneKey: string;
  actionId: string;
  evidence: JsonObject;
}

export type ExperienceMilestoneResult =
  | { status: "accepted"; eventId?: string }
  | { status: "duplicate"; eventId?: string }
  | { status: "unavailable"; reason: string };

export interface ExperienceMilestoneSource {
  record(request: ExperienceMilestoneRequest): Promise<ExperienceMilestoneResult>;
}

/** Track C integration: modules describe needs; the host onboarding framework owns completion. */
export type ExperienceOnboardingResult =
  | { status: "accepted" }
  | { status: "unavailable"; reason: string };

export interface ExperienceOnboardingBridge {
  completeStep(input: {
    experienceId: string;
    moduleId: string;
    stepId: string;
    result: JsonObject;
  }): Promise<ExperienceOnboardingResult>;
}

/** Track E/platform integration: safe diagnostics without private module payloads. */
export interface ExperienceRecoverableErrorReporter {
  report(input: {
    code: string;
    experienceId: string;
    moduleId: string;
    safeContext?: JsonObject;
  }): void | Promise<void>;
}

export interface ExperienceModuleRenderContext {
  experience: Experience;
  manifest: ExperienceModuleManifest;
  route: ExperienceRouteDefinition;
  configuration: JsonObject;
  accessMode: ExperienceAccessMode;
  authenticated: boolean;
  locale: string;
  timeZone: string;
  organizationId?: string;
  identityId?: string;
  customerId?: string;
  canUse: (capabilityKey: string) => ExperienceCapabilityDecision;
  requestRegistration: (returnPath?: string) => void;
  requestUpgrade: (capabilityKey: string) => void;
  submitEvent: (name: ExperienceModuleEventType, properties?: JsonObject, idempotencyKey?: string) => boolean;
  /**
   * Requests a global milestone through the trusted server adapter. The module's
   * evidence is only a candidate; the owning server validator must accept it.
   */
  reachMilestone: (milestoneKey: string, actionId: string, evidence: JsonObject) => Promise<ExperienceMilestoneResult>;
  completeOnboardingStep: (stepId: string, result: JsonObject) => Promise<ExperienceOnboardingResult>;
  runProtectedOperation: (operation: string) => Promise<JsonObject>;
  renderMedia: (asset: ExperienceMediaAsset) => ReactNode;
  reportRecoverableError: (code: string, safeContext?: JsonObject) => void;
}

export interface ExperienceModule {
  manifest: ExperienceModuleManifest;
  render(context: ExperienceModuleRenderContext): ReactNode;
}

export interface ExperienceModuleRegistration {
  id: string;
  moduleVersion: string;
  slot: ExperienceSlot;
  defaultConfiguration: JsonObject;
  loader: () => Promise<ExperienceModule>;
}
