import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { useOrganization } from "../context/OrganizationContext";
import { demoOffers, demoReferrals } from "../data/demo";
import { Badge, Button, Card, EmptyState, Input, MetricCard, PageHeader, Select, TextArea } from "../components/ui";
import { Link, navigate } from "../router";

const pageCopy: Record<string, { title: string; description: string; eyebrow?: string }> = {
  "/app": { title: "Welcome back", description: "Your Nurture home brings the next meaningful action from across the customer lifecycle into one place.", eyebrow: "Home" },
  "/app/experience": { title: "The App Experience", description: "Primary module container for future organization-specific or general Nurture experiences.", eyebrow: "Stage 4" },
  "/app/secondary": { title: "Secondary Experience", description: "A continuation container for resources, companion modules, advanced content, or relationship development.", eyebrow: "Stage 5" },
  "/app/offers": { title: "Offers & Upgrade", description: "Continuation, upgrade, and recurring offers can appear here based on participant eligibility.", eyebrow: "Stage 6" },
  "/app/notifications": { title: "Notifications", description: "Organization messages, experience updates, survey requests, offers, and referral acknowledgements share one inbox.", eyebrow: "Inbox" },
  "/app/referrals": { title: "Referrals", description: "Share a durable attribution link and follow the status of introductions you make.", eyebrow: "Stage 7" },
  "/app/feedback": { title: "Send feedback", description: "Report an issue, suggest an idea, or tell us about your Nurture experience.", eyebrow: "Feedback" },
  "/app/account": { title: "Account", description: "Your account hub for profile, organization membership, security, billing, privacy, support, and sign out.", eyebrow: "Account" },
  "/app/profile": { title: "Profile", description: "Keep the minimum personal information needed for your account and experiences up to date.", eyebrow: "Account" },
  "/app/settings": { title: "Settings", description: "Manage communications, privacy preferences, theme readiness, and account security entry points.", eyebrow: "Account" },
  "/app/billing": { title: "Billing", description: "Subscription and billing information is presented here; Stripe operations remain behind a server-side service boundary.", eyebrow: "Account" },
  "/app/help": { title: "Help", description: "Get help with your account, experiences, organization membership, billing, and privacy.", eyebrow: "Support" },
};
export function CustomerPage({ path }: { path: string }) { const { currentUser } = useAuth(); const { organization } = useOrganization(); const page = pageCopy[path] ?? pageCopy["/app"]; return <><PageHeader eyebrow={page.eyebrow} title={page.title} description={page.description} />{path === "/app" ? <Home /> : path === "/app/experience" ? <Experience secondary={false} /> : path === "/app/secondary" ? <Experience secondary /> : path === "/app/offers" ? <Offers /> : path === "/app/notifications" ? <Notifications /> : path === "/app/referrals" ? <Referrals /> : path === "/app/feedback" ? <FeedbackForm /> : path === "/app/account" ? <Account /> : path === "/app/profile" ? <Profile name={currentUser?.displayName ?? "User"} email={currentUser?.email ?? ""} organization={organization?.name} /> : path === "/app/settings" ? <Settings /> : path === "/app/billing" ? <Billing /> : <Help />}</>; }
function Home() { return <><div className="metric-grid"><MetricCard label="Current stage" value="4" detail="App Experience" /><MetricCard label="Next action" value="Continue" detail="Core experience" /><MetricCard label="Notifications" value="3" detail="1 needs action" /></div><div className="two-column"><Card><Badge tone="accent">In progress</Badge><h2>Core Experience</h2><p>Continue where you left off. Future modules can own progress and state inside this container.</p><Link className="button" href="/app/experience">Continue experience</Link></Card><Card><h2>Your lifecycle</h2><ol className="compact-steps"><li className="done">Registration complete</li><li className="active">Primary experience</li><li>Secondary experience</li><li>Feedback + referral</li></ol></Card></div><Card><div className="card-heading"><div><p className="eyebrow">Next</p><h2>Share feedback when you are ready</h2></div><Link href="/app/feedback">Open feedback →</Link></div></Card></>; }
function Experience({ secondary }: { secondary: boolean }) { return <Card className="module-container"><Badge tone="accent">Module container</Badge><h2>{secondary ? "Secondary Experience Module" : "Primary Experience Module"}</h2><p>This shell reserves navigation, identity, organization context, responsive layout, and lifecycle entry/exit points while allowing the actual future app module to own its interface.</p><div className="module-placeholder"><span aria-hidden="true">N</span><strong>Future experience renders here</strong><small>Assessment · course · coaching · event · workflow · membership · other module</small></div></Card>; }
function Offers() { return <div className="pricing-grid">{demoOffers.map((offer) => <Card key={offer.id}><Badge>{offer.type}</Badge><h2>{offer.name}</h2><p>{offer.description}</p><strong className="price">{offer.priceLabel}</strong><Button disabled>Choose offer</Button><small>Stripe checkout is a future server-created session.</small></Card>)}</div>; }
function Notifications() { return <Card><div className="notification-row"><Badge tone="accent">Action</Badge><div><strong>Feedback requested</strong><p>Tell Nurture Demo Organization about your recent experience.</p></div><Link href="/app/feedback">Respond</Link></div><div className="notification-row"><Badge>Update</Badge><div><strong>Secondary experience ready</strong><p>Your next experience is available.</p></div><Link href="/app/secondary">Open</Link></div><div className="notification-row"><Badge>Referral</Badge><div><strong>Your introduction visited</strong><p>Referral attribution is active for one recent visitor.</p></div><Link href="/app/referrals">View</Link></div></Card>; }
function Referrals() { return <><Card><h2>Your referral link</h2><code>https://nurture.accelanalysis.com/r/JORDAN-NURTURE</code><p className="muted">The code carries attribution through public pages and registration.</p><Button className="button-secondary">Copy link</Button></Card><div className="feature-list">{demoReferrals.map((referral) => <Card key={referral.id}><Badge tone={referral.status === "converted" ? "positive" : "neutral"}>{referral.status}</Badge><h3>{referral.referralCode}</h3><p>{referral.campaign}</p></Card>)}</div></>; }
function FeedbackForm() { const [sent, setSent] = useState(false); return sent ? <EmptyState title="Feedback captured" description="This demo confirms the workflow. Production persistence and attachment upload will connect through the feedback service." /> : <Card className="form-card"><label>Category<Select><option>Experience</option><option>Bug</option><option>Billing</option><option>Idea</option><option>Other</option></Select></label><label>Message<TextArea rows={6} /></label><label>Optional screenshot or file<Input type="file" /></label><Button onClick={() => setSent(true)}>Submit feedback</Button><small>Screen, app version, and appropriate browser metadata can be attached automatically at submission time.</small></Card>; }
function Account() { const { signOut } = useAuth(); const logout = async () => { await signOut(); navigate("/"); }; return <><div className="feature-list">{[["Profile", "/app/profile"], ["Settings", "/app/settings"], ["Billing", "/app/billing"], ["Help", "/app/help"]].map(([label, href]) => <Card key={href}><h3>{label}</h3><p>Manage this part of your Nurture account.</p><Link href={href}>Open {label.toLowerCase()} →</Link></Card>)}</div><Card><h2>Session</h2><p>End this session on the current device.</p><Button className="button-secondary" onClick={logout}>Sign Out</Button></Card></>; }
function Profile({ name, email, organization }: { name: string; email: string; organization?: string }) { return <div className="two-column"><Card className="form-card"><label>Display name<Input defaultValue={name} /></label><label>Email<Input type="email" defaultValue={email} /></label><label>Phone<Input type="tel" placeholder="Optional" /></label><Button>Save profile</Button></Card><Card><h2>Organization</h2><p>{organization ?? "No default organization"}</p><p className="muted">Membership is separate from the user profile so a person can belong to multiple organizations.</p></Card></div>; }
function Settings() { return <div className="settings-list"><Card><h2>Communication</h2><label className="toggle-row"><span>Email notifications</span><input type="checkbox" defaultChecked /></label><label className="toggle-row"><span>SMS notifications</span><input type="checkbox" /></label><label className="toggle-row"><span>Push notifications</span><input type="checkbox" defaultChecked /></label></Card><Card><h2>Privacy & data</h2><p>Download data, review consent history, and request account deletion.</p><Button className="button-secondary">Privacy controls</Button></Card><Card><h2>Security</h2><p>Authentication methods, passkeys, connected providers, and active sessions will live here.</p><Button className="button-secondary">Security options</Button></Card></div>; }
function Billing() { return <Card><Badge tone="accent">Skeleton</Badge><h2>Nurture Plus</h2><p>No live Stripe session is created. The billing UI is ready to call a server-side checkout or customer-portal service when payment integration begins.</p><Button disabled>Manage billing</Button></Card>; }
function Help() { return <div className="feature-list">{["Getting started", "Experiences", "Organization access", "Billing", "Privacy & data", "Contact support"].map((item) => <Card key={item}><h3>{item}</h3><p>Help article placeholder with a durable route destination.</p></Card>)}</div>; }
