import { useState, type FormEvent, type ReactNode } from "react";
import { Card, Button, Input, PageHeader, Select } from "../components/ui";
import { Link, navigate, useRoute } from "../router";
import { useAuth } from "../context/AuthContext";
import { authService } from "../services/authService";
import type { OrganizationRole } from "../types/models";

export function AuthPage({ mode }: { mode: "login" | "register" | "forgot" | "verify" }) { const { signInDemo } = useAuth(); const route = useRoute(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false); const returnTo = route.query.get("returnTo") || "/app"; const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(null); try { if (mode === "login") await authService.signIn(email, password); if (mode === "register") await authService.register(email, password); if (mode === "forgot") { await authService.resetPassword(email); setMessage("Password reset instructions requested. Check your email if this account exists."); return; } navigate(returnTo); } catch (reason: unknown) { setMessage(reason instanceof Error ? reason.message : "Unable to continue."); } finally { setBusy(false); } };
  if (mode === "verify") return <AuthFrame><PageHeader eyebrow="Account" title="Verify your email" description="Email verification is represented as a dedicated state so onboarding can pause here when required." /><Card><p>When Firebase email verification is enabled for an account, this route will confirm status and offer resend actions.</p><Button onClick={() => authService.sendVerification().then(() => setMessage("Verification email requested.")).catch((error: Error) => setMessage(error.message))}>Resend verification</Button>{message ? <p className="form-message">{message}</p> : null}</Card></AuthFrame>;
  const title = mode === "login" ? "Sign in" : mode === "register" ? "Create your Nurture account" : "Reset your password"; const description = mode === "login" ? "Continue to your app experience or organization workspace." : mode === "register" ? "Create an individual account now; organization creation and invitations attach through membership records." : "Enter your email to request a password reset.";
  return <AuthFrame><PageHeader eyebrow="Nurture account" title={title} description={description} /><Card className="form-card"><form onSubmit={submit}><label>Email<Input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label>{mode !== "forgot" ? <label>Password<Input required type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} /></label> : null}<Button disabled={busy}>{busy ? "Working…" : mode === "login" ? "Sign in" : mode === "register" ? "Create account" : "Send reset link"}</Button></form>{message ? <p className="form-message">{message}</p> : null}{mode === "login" ? <><div className="divider"><span>or review the skeleton</span></div><div className="demo-actions"><Button className="button-secondary" onClick={() => { signInDemo("member"); navigate("/app"); }}>Customer demo</Button><Button className="button-secondary" onClick={() => { signInDemo("owner"); navigate("/org/nurture-demo/dashboard"); }}>Organization admin demo</Button></div><p><Link href="/forgot-password">Forgot password?</Link> · <Link href="/register">Create account</Link></p></> : mode === "register" ? <p>Already registered? <Link href="/login">Sign in</Link></p> : <p><Link href="/login">Back to sign in</Link></p>}</Card></AuthFrame>; }
function AuthFrame({ children }: { children: ReactNode }) { return <main className="auth-shell"><Link className="brand" href="/"><img src="/brand/logo/nurture-n.svg" alt="" /><span>Nurture</span></Link><section className="auth-card-wrap">{children}</section></main>; }
export function InvitationPage({ invitationId }: { invitationId: string }) { const { signInDemo } = useAuth(); const [state, setState] = useState<"pending" | "expired" | "accepted">(invitationId.includes("expired") ? "expired" : invitationId.includes("accepted") ? "accepted" : "pending"); return <AuthFrame><PageHeader eyebrow="Organization invitation" title={state === "pending" ? "Join Nurture Demo Organization" : state === "expired" ? "This invitation expired" : "Invitation already accepted"} description={state === "pending" ? "Accepting creates or links a Nurture account, then establishes an organization membership." : state === "expired" ? "Ask the organization administrator to send a new invitation." : "Sign in with the account that accepted the invitation."} /><Card>{state === "pending" ? <><label>Role<Select value="manager" disabled><option>Manager</option></Select></label><Button onClick={() => { signInDemo("manager" as OrganizationRole); setState("accepted"); navigate("/org/nurture-demo/dashboard"); }}>Accept invitation</Button></> : <Link className="button" href="/login">Go to sign in</Link>}<p className="muted">Invitation ID: {invitationId}</p></Card></AuthFrame>; }
