import { useState } from "react";
import { demoOffers, demoSurvey, pipelineStages } from "../data/demo";
import { Link, navigate } from "../router";
import { Badge, Button, Card, Input, PageHeader, TextArea } from "../components/ui";

export function MarketingHome() { return <><section className="hero content-width"><Badge tone="accent">Seven-stage customer lifecycle</Badge><h1>Build relationships that keep moving forward.</h1><p>Nurture connects discovery, offers, onboarding, app experiences, recurring value, feedback, and referral in one coherent application hub.</p><div className="hero-actions"><Link className="button" href="/experience">Start an Experience</Link><Link className="button button-secondary" href="/features">Nurture for Organizations</Link></div></section><section className="content-width section"><div className="section-heading"><p className="eyebrow">Customer pipeline</p><h2>One continuous lifecycle.</h2><p>The public acquisition journey and customer app lifecycle meet inside the App Experience, allowing anonymous, free, or trial participation before registration.</p></div><div className="pipeline-public">{pipelineStages.map((stage) => <Link href={stage.number === 1 ? "/" : stage.number === 2 ? "/offers" : stage.number === 3 ? "/register" : stage.number === 4 ? "/experience" : stage.number === 7 ? "/app/feedback" : "/features"} key={stage.number}><span>{stage.number}</span><strong>{stage.name}</strong><small>{stage.detail}</small></Link>)}</div></section><section className="content-width section two-column"><Card><p className="eyebrow">For participants</p><h2>Start with value, not friction.</h2><p>Enter a public or trial experience, then register only when an account adds value. Referral context can survive the transition.</p><Link href="/experience">Preview the experience →</Link></Card><Card><p className="eyebrow">For organizations</p><h2>Operate the relationship.</h2><p>Maintain contacts, sequences, templates, surveys, offers, referrals, permissions, and lifecycle insights from one tenant-aware workspace.</p><Link href="/login">Open the admin demo →</Link></Card></section><section className="content-width section cta-panel"><div><p className="eyebrow">Continue the lifecycle</p><h2>Begin with an experience or an offer.</h2></div><div className="hero-actions"><Link className="button" href="/experience">Start experience</Link><Link className="button button-secondary" href="/offers">View offers</Link></div></section></>; }

const copy: Record<string, { title: string; description: string; bullets?: string[] }> = {
  "/features": { title: "A hub for the whole customer journey", description: "Nurture provides reusable product, organization, outreach, feedback, referral, and account foundations around installable experiences.", bullets: ["Experience containers", "Organization administration", "Contact lifecycle", "Sequences & templates", "Surveys & feedback", "Offers & referrals"] },
  "/how-it-works": { title: "From acquisition to advocacy", description: "Marketing leads to offers and registration, then into primary and secondary experiences, recurring value, feedback, and referrals that feed the next acquisition cycle.", bullets: pipelineStages.map((stage) => `${stage.number}. ${stage.name}`) },
  "/about": { title: "About Nurture", description: "Nurture is a general-purpose application hub designed to help organizations deliver experiences and continue customer relationships around them." },
  "/help": { title: "Help & FAQ", description: "A durable home for getting-started, account, experience, organization, billing, privacy, and support content." },
  "/contact": { title: "Contact", description: "A future support and sales contact surface. This skeleton intentionally does not send messages yet." },
  "/privacy": { title: "Privacy", description: "Placeholder for the production privacy notice, consent disclosures, retention policies, data rights, and processor information." },
  "/terms": { title: "Terms", description: "Placeholder for the production terms governing Nurture accounts, organization workspaces, experiences, offers, and referrals." },
};
export function PublicInfoPage({ path }: { path: string }) { const page = copy[path] ?? copy["/features"]; return <section className="content-width page-section"><PageHeader eyebrow="Nurture" title={page.title} description={page.description} />{page.bullets ? <div className="feature-list">{page.bullets.map((item) => <Card key={item}><h3>{item}</h3><p>Architecture and production behavior will be implemented incrementally on this foundation.</p></Card>)}</div> : null}{path === "/contact" ? <Card className="form-card"><label>Name<Input /></label><label>Email<Input type="email" /></label><label>Message<TextArea rows={5} /></label><Button>Send message</Button><small>Placeholder form — delivery is not enabled in the skeleton.</small></Card> : null}</section>; }
export function PublicOffersPage() { return <section className="content-width page-section"><PageHeader eyebrow="Stage 2" title="Offers" description="Free, trial, one-time, subscription, upgrade, and organization-specific offers share one entitlement-friendly model." /><div className="pricing-grid">{demoOffers.map((offer) => <Card key={offer.id}><Badge>{offer.type}</Badge><h2>{offer.name}</h2><p>{offer.description}</p><strong className="price">{offer.priceLabel}</strong><ul>{offer.entitlements.map((item) => <li key={item}>{item}</li>)}</ul><Button onClick={() => navigate(`/offers/${offer.id}`)}>View offer</Button></Card>)}</div></section>; }
export function PublicOfferDetail({ offerId }: { offerId: string }) { const offer = demoOffers.find((item) => item.id === offerId) ?? demoOffers[0]; return <section className="content-width page-section narrow"><PageHeader eyebrow="Offer" title={offer.name} description={offer.description} /><Card><Badge tone="accent">{offer.type}</Badge><p className="price">{offer.priceLabel}</p><ul>{offer.entitlements.map((item) => <li key={item}>{item}</li>)}</ul><Button onClick={() => navigate("/register")}>Continue</Button><p className="muted">Checkout is intentionally not live in this skeleton.</p></Card></section>; }
export function PublicExperience() { const [progress, setProgress] = useState(1); return <section className="content-width page-section narrow"><PageHeader eyebrow="Stage 4 · Public / trial boundary" title="The App Experience" description="A polished placeholder container for future installable or organization-specific experience modules." /><Card className="experience-card"><div className="experience-progress"><span>Preview step {progress} of 3</span><progress max={3} value={progress} /></div><h2>{progress === 1 ? "Welcome to the experience" : progress === 2 ? "A meaningful interaction belongs here" : "Continue your relationship"}</h2><p>{progress === 1 ? "This public preview demonstrates that an experience can begin before registration." : progress === 2 ? "Future modules can render assessments, learning, coaching, events, workflows, or other app-specific experiences inside this shell." : "Nurture can ask the participant to create an account, accept an invitation, or choose an offer without losing referral attribution."}</p><div className="hero-actions">{progress < 3 ? <Button onClick={() => setProgress((value) => value + 1)}>Continue</Button> : <Button onClick={() => navigate("/register")}>Create account</Button>}<Link href="/offers">View offers</Link></div></Card></section>; }
export function ReferralLanding({ code }: { code: string }) { sessionStorage.setItem("nurture-referral-code", code); return <section className="content-width page-section narrow"><PageHeader eyebrow="Referral" title="You were invited to Nurture" description="Referral attribution is preserved for this browser session and can follow the visitor through registration and future conversion." /><Card><p><strong>Referral code</strong></p><code>{code}</code><div className="hero-actions"><Link className="button" href="/experience">Start experience</Link><Link href="/register">Create account</Link></div></Card></section>; }
export function PublicSurvey({ surveyId }: { surveyId: string }) { const survey = demoSurvey; return <section className="content-width page-section narrow"><PageHeader eyebrow={`Survey ${surveyId}`} title={survey.title} description={survey.description} /><Card className="form-card">{survey.questions.map((question) => <label key={question.id}>{question.prompt}{question.type === "long-text" ? <TextArea rows={4} /> : question.type === "yes-no" ? <select className="input"><option>Choose…</option><option>Yes</option><option>No</option></select> : <Input placeholder={question.type === "nps" ? "0–10" : "Your response"} />}</label>)}<Button>Submit feedback</Button><small>Response persistence is a service boundary in this skeleton.</small></Card></section>; }
