export const COMMUNICATION_SCHEMA_VERSION = 1 as const;

export const communicationExecutionModes = ["live", "test", "preview", "demo", "development"] as const;
export type CommunicationExecutionMode = (typeof communicationExecutionModes)[number];

export const communicationPurposes = ["transactional", "marketing"] as const;
export type CommunicationPurpose = (typeof communicationPurposes)[number];

export const communicationTemplateIds = [
  "registration-welcome",
  "onboarding-reminder",
  "lead-follow-up",
  "activation-invitation",
  "trial-conversion",
  "checkout-recovery",
  "survey-invitation",
  "survey-reminder",
  "survey-thanks",
  "feedback-recovery",
  "referral-invitation",
  "referral-status",
  "referral-reward-issued",
  "referral-reward-reversed",
] as const;
export type CommunicationTemplateId = (typeof communicationTemplateIds)[number];

export const communicationVariableKeys = [
  "organization.name",
  "customer.firstName",
  "customer.displayName",
  "lead.firstName",
  "experience.name",
  "experience.startUrl",
  "onboarding.resumeUrl",
  "offer.name",
  "offer.checkoutUrl",
  "trial.endDate",
  "application.publicUrl",
  "preferences.url",
  "support.email",
  "survey.title",
  "survey.url",
  "referral.centerUrl",
] as const;
export type CommunicationVariableKey = (typeof communicationVariableKeys)[number];
export type CommunicationVariableValues = Partial<Record<CommunicationVariableKey, string>>;

export interface EmailTemplateContent {
  name: string;
  subject: string;
  /** Plain text is canonical. HTML is generated by Nurture after escaping. */
  body: string;
  variables: CommunicationVariableKey[];
}

export interface EmailTemplateDraft {
  templateId: CommunicationTemplateId;
  purpose: CommunicationPurpose;
  content: EmailTemplateContent;
  updatedAt: string;
  inheritedFromDefaultVersion?: string;
}

export interface EmailTemplatePublishedVersion {
  schemaVersion: typeof COMMUNICATION_SCHEMA_VERSION;
  organizationId: string;
  templateId: CommunicationTemplateId;
  purpose: CommunicationPurpose;
  version: number;
  content: EmailTemplateContent;
  sourceDraftUpdatedAt: string;
  publishedAt: string;
  publishedBy: string;
}

export interface CommunicationTemplateView {
  templateId: CommunicationTemplateId;
  purpose: CommunicationPurpose;
  defaultVersion: string;
  provenance: "nurture-default" | "organization-override";
  draft: EmailTemplateDraft;
  published: EmailTemplatePublishedVersion | null;
  versions: EmailTemplatePublishedVersion[];
}

export type SenderReadinessStatus = "ready" | "not-configured" | "pending" | "blocked";
export interface EmailSenderReadiness {
  organizationId: string;
  provider: "sendgrid";
  status: SenderReadinessStatus;
  fromAddress?: string;
  fromName?: string;
  authenticatedDomain?: string;
  verifiedAt?: string;
  reason?: string;
}

export type ConsentDecision = "granted" | "denied" | "unknown" | "not-required";
export interface EmailConsentSnapshot {
  decision: ConsentDecision;
  purpose: CommunicationPurpose;
  source: string;
  observedAt: string;
  policyVersion?: string;
}

export interface EmailSuppressionSnapshot {
  suppressed: boolean;
  scope: "platform" | "organization" | "none";
  reason?: string;
  observedAt: string;
}

export type EmailEligibilityOutcome = "eligible" | "hold" | "suppress";
export type EmailEligibilityReason =
  | "eligible"
  | "non-delivery-mode"
  | "recipient-unavailable"
  | "sender-not-ready"
  | "provider-suppressed"
  | "test-recipient-required"
  | "test-recipient-not-allowlisted"
  | "consent-unknown"
  | "consent-withdrawn"
  | "purpose-mismatch";

export interface EmailEligibilityInput {
  mode: CommunicationExecutionMode;
  purpose: CommunicationPurpose;
  templatePurpose: CommunicationPurpose;
  recipientKind: "customer" | "lead" | "test";
  recipientAvailable: boolean;
  sender: EmailSenderReadiness;
  consent: EmailConsentSnapshot;
  suppression: EmailSuppressionSnapshot;
  testAllowlisted?: boolean;
}

export interface EmailEligibilityResult {
  outcome: EmailEligibilityOutcome;
  reason: EmailEligibilityReason;
  explanation: string;
}

export interface CommunicationRecipientReference {
  kind: "customer" | "lead" | "test";
  id: string;
}

export interface CommunicationTriggerReference {
  runId?: string;
  eventId?: string;
}

export interface MessageIntent {
  schemaVersion: typeof COMMUNICATION_SCHEMA_VERSION;
  messageId: string;
  organizationId: string;
  mode: CommunicationExecutionMode;
  purpose: CommunicationPurpose;
  recipient: CommunicationRecipientReference;
  /** SHA-256 of normalized email. Raw recipient address is not persisted here. */
  recipientHash: string;
  templateId: CommunicationTemplateId;
  templateVersion: number;
  variables: CommunicationVariableValues;
  trigger?: CommunicationTriggerReference;
  /** Stable logical effect identity supplied by the trusted scheduler/caller. */
  effectId: string;
  createdAt: string;
}

export type MessageDeliveryStatus =
  | "planned"
  | "held"
  | "suppressed"
  | "submitting"
  | "accepted"
  | "deferred"
  | "delivered"
  | "bounced"
  | "dropped"
  | "complained"
  | "unsubscribed"
  | "failed"
  | "unknown"
  | "cancelled";

export interface MessageDeliveryAttempt {
  attempt: number;
  startedAt: string;
  completedAt?: string;
  outcome: "accepted" | "retryable-failure" | "terminal-failure" | "unknown";
  providerRequestId?: string;
  retryAfterMs?: number;
  reason?: string;
}

export interface MessageDeliveryRecord {
  intent: MessageIntent;
  status: MessageDeliveryStatus;
  statusReason?: string;
  attempts: MessageDeliveryAttempt[];
  provider?: "sendgrid";
  providerMessageId?: string;
  acceptedAt?: string;
  deliveredAt?: string;
  updatedAt: string;
}

export interface EmailPreferenceView {
  organizationId: string;
  organizationName: string;
  marketing: "granted" | "denied" | "unknown";
  service: "granted" | "denied" | "unknown";
  updatedAt?: string;
}

export interface EmailPreferencePort {
  read(token: string): Promise<EmailPreferenceView>;
  updateMarketing(token: string, allowed: boolean): Promise<EmailPreferenceView>;
}
