import { LIFECYCLE_ACQUISITION_CATALOG_VERSION, type LifecycleAutomationCatalogEntry, type LifecycleAutomationConfiguration, type LifecycleRunExplanation, type LifecycleTemplateSummary, type LifecycleWorkspaceSnapshot } from "./contracts";

export const lifecycleAcquisitionCatalog: LifecycleAutomationCatalogEntry[] = [
  { id:"R2-WELCOME", label:"Registration welcome", intent:"A bounded welcome after a trusted registration completes.", triggerLabel:"Trusted registration completed", messagePurpose:"service", timingChoices:[{ id:"immediate", label:"Immediately", description:"Queue after trusted registration processing completes", offsetMinutes:0 },{ id:"after-15-min", label:"After 15 minutes", description:"Short durable delay after registration", offsetMinutes:15 }], conditionChoices:[{ id:"account-exists", label:"Account still exists", description:"Recheck the current customer/account relationship", required:true },{ id:"recipient-eligible", label:"Recipient is eligible", description:"Use Track D's current service-email eligibility result", required:true },{ id:"organization-active", label:"Organization is active", description:"Stop if the tenant is paused or unavailable", required:true }] },
  { id:"R2-LEAD", label:"Lead-to-registration follow-up", intent:"Invite a permitted lead to register while the lead remains unregistered.", triggerLabel:"Permitted lead captured", messagePurpose:"promotional", timingChoices:[{ id:"after-1-day", label:"After 1 day", description:"Recheck registration and permission after a durable one-day delay", offsetMinutes:1440 },{ id:"after-3-days", label:"After 3 days", description:"Recheck registration and permission after three days", offsetMinutes:4320 }], conditionChoices:[{ id:"still-unregistered", label:"Still unregistered", description:"Stop after verified registration", required:true },{ id:"contact-permitted", label:"Promotional email remains permitted", description:"Current tenant-scoped consent must permit this purpose", required:true },{ id:"not-suppressed", label:"Not provider-suppressed", description:"Respect current provider/account suppression scope", required:true }] },
  { id:"R2-ACTIVATE", label:"First-use activation", intent:"Invite a registered customer to the Experience before validated first meaningful use.", triggerLabel:"Trusted registration completed without first meaningful use", messagePurpose:"promotional", timingChoices:[{ id:"after-1-day", label:"After 1 day", description:"Check for first meaningful use after one day", offsetMinutes:1440 },{ id:"after-3-days", label:"After 3 days", description:"Check for first meaningful use after three days", offsetMinutes:4320 }], conditionChoices:[{ id:"not-activated", label:"No validated first meaningful use", description:"Track B/F activation evidence still absent", required:true },{ id:"contact-permitted", label:"Promotional email remains permitted", description:"Use current Track C consent and Track D eligibility", required:true },{ id:"commercial-offer-valid", label:"Any offered trial/access path is currently valid", description:"Do not imply a trial that does not exist", required:true }] },
  { id:"R2-ONBOARD", label:"Incomplete onboarding reminder", intent:"Remind a customer only while the same relevant onboarding flow remains incomplete.", triggerLabel:"Trusted onboarding started", messagePurpose:"promotional", timingChoices:[{ id:"after-1-day", label:"After 1 day", description:"Recheck the pinned onboarding flow after one day", offsetMinutes:1440 },{ id:"after-3-days", label:"After 3 days", description:"Recheck the pinned onboarding flow after three days", offsetMinutes:4320 }], conditionChoices:[{ id:"same-flow-incomplete", label:"Same flow is still incomplete", description:"Stop after completion or incompatible flow change", required:true },{ id:"contact-permitted", label:"Promotional email remains permitted", description:"Current purpose-specific eligibility must pass", required:true },{ id:"customer-active", label:"Customer relationship remains active", description:"Do not send after deletion or loss of scope", required:true }] },
  { id:"R2-TRIAL", label:"Actual-trial conversion", intent:"Send a bounded conversion message relative to a trusted actual-trial end.", triggerLabel:"Trusted actual trial with verified end time", messagePurpose:"promotional", timingChoices:[{ id:"before-24-hours", label:"24 hours before trial end", description:"Requires a trusted future trial end", offsetMinutes:-1440 },{ id:"before-6-hours", label:"6 hours before trial end", description:"Requires a trusted future trial end", offsetMinutes:-360 }], conditionChoices:[{ id:"still-trialing", label:"Still trialing", description:"Current trusted commercial state remains trialing", required:true },{ id:"not-converted", label:"No completed purchase", description:"Stop after verified conversion", required:true },{ id:"trusted-trial-end", label:"Trusted trial end is still valid", description:"Do not infer trial timing from page entry", required:true },{ id:"contact-permitted", label:"Promotional email remains permitted", description:"Current purpose-specific eligibility must pass", required:true }] },
  { id:"R2-CHECKOUT", label:"Checkout recovery", intent:"Recover a trusted incomplete checkout only after a current no-purchase check.", triggerLabel:"Trusted checkout attempt", messagePurpose:"promotional", timingChoices:[{ id:"after-1-hour", label:"After 1 hour", description:"Durable delay followed by a current no-purchase check", offsetMinutes:60 },{ id:"after-1-day", label:"After 1 day", description:"Durable delay followed by a current no-purchase check", offsetMinutes:1440 }], conditionChoices:[{ id:"no-purchase", label:"No completed purchase", description:"Use current trusted Release 1 commercial state", required:true },{ id:"contactable", label:"Recipient remains contactable", description:"Anonymous or uncontactable users cannot receive recovery email", required:true },{ id:"contact-permitted", label:"Promotional email remains permitted", description:"Current purpose-specific eligibility must pass", required:true }] },
];

export const lifecycleTemplateFixture: LifecycleTemplateSummary[] = [
  { templateId:"tpl-welcome-service", label:"Welcome to {{organization.name}}", purpose:"service", publishedVersion:"tpl-v1", readiness:"ready", readinessExplanation:"Published service template fixture." },
  { templateId:"tpl-lead-register", label:"Continue with your account", purpose:"promotional", publishedVersion:"tpl-v2", readiness:"ready", readinessExplanation:"Published promotional template fixture." },
  { templateId:"tpl-activate", label:"Start your Experience", purpose:"promotional", publishedVersion:"tpl-v1", readiness:"ready", readinessExplanation:"Published promotional template fixture." },
  { templateId:"tpl-onboarding", label:"Finish getting started", purpose:"promotional", publishedVersion:"tpl-v3", readiness:"ready", readinessExplanation:"Published promotional template fixture." },
  { templateId:"tpl-trial", label:"Your actual trial is ending", purpose:"promotional", publishedVersion:"tpl-v1", readiness:"ready", readinessExplanation:"Published promotional template fixture." },
  { templateId:"tpl-checkout", label:"Complete your checkout", purpose:"promotional", publishedVersion:"tpl-v2", readiness:"ready", readinessExplanation:"Published promotional template fixture." },
];
function requiredConditions(entry: LifecycleAutomationCatalogEntry) { return entry.conditionChoices.filter((condition) => condition.required).map((condition) => condition.id); }
const templateByAutomation: Record<LifecycleAutomationConfiguration["automationId"], string> = { "R2-WELCOME":"tpl-welcome-service", "R2-LEAD":"tpl-lead-register", "R2-ACTIVATE":"tpl-activate", "R2-ONBOARD":"tpl-onboarding", "R2-TRIAL":"tpl-trial", "R2-CHECKOUT":"tpl-checkout" };
export const lifecycleDefaultConfiguration: LifecycleAutomationConfiguration[] = lifecycleAcquisitionCatalog.map((entry) => ({ automationId:entry.id, enabled:false, timingId:entry.timingChoices[0]!.id, templateId:templateByAutomation[entry.id], selectedConditionIds:requiredConditions(entry) }));
export const lifecycleRunHistoryFixture: LifecycleRunExplanation[] = [
  { runId:"run-ava-checkout", customerId:"cust-ava-patel", automationId:"R2-CHECKOUT", automationLabel:"Checkout recovery", status:"cancelled", reason:"Cancelled because the trusted purchase completed during the configured recovery delay.", pinnedVersion:"lifecycle-v1", updatedAt:"2026-09-04T13:02:30Z" },
  { runId:"run-noah-onboarding", customerId:"cust-noah-williams", automationId:"R2-ONBOARD", automationLabel:"Incomplete onboarding reminder", status:"suppressed", reason:"Final dispatch admission rejected promotional email after consent was withdrawn.", pinnedVersion:"lifecycle-v1", updatedAt:"2026-09-04T10:12:00Z" },
  { runId:"run-liam-lead", customerId:"cust-liam-rivera", automationId:"R2-LEAD", automationLabel:"Lead-to-registration follow-up", status:"scheduled", reason:"Waiting for the configured delay; registration and permission will be rechecked before dispatch.", pinnedVersion:"lifecycle-v1", updatedAt:"2026-09-05T11:06:00Z", nextActionAt:"2026-09-06T11:05:00Z" },
];
function clone<T>(value:T):T { return JSON.parse(JSON.stringify(value)) as T; }
export function createLifecycleWorkspaceFixture(organizationId:string): LifecycleWorkspaceSnapshot { const defaults=clone(lifecycleDefaultConfiguration); return { organizationId, catalogVersion:LIFECYCLE_ACQUISITION_CATALOG_VERSION, catalog:clone(lifecycleAcquisitionCatalog), defaults, draft:clone(defaults), draftRevision:1, published:null, templates:clone(lifecycleTemplateFixture), runHistory:organizationId === "nurture-demo" ? clone(lifecycleRunHistoryFixture) : [], outboundActivation:{ status:"disabled", explanation:"Outbound campaigns remain disabled until sender readiness, permission, suppression, and explicit runtime activation all pass." } }; }
