import { useEffect, useMemo, useRef, useState } from "react";
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState, PageHeader, Select, Tabs } from "../../components/ui";
import { Link } from "../../router";
import { automationPreviewLines, lifecycleConfigurationProvenance, validateLifecycleDraft, type LifecycleAutomationConfiguration, type LifecycleAutomationId, type LifecycleConfigurationValidationIssue, type LifecycleWorkspaceSnapshot } from "./contracts";
import { lifecycleAutomationPort } from "./port";
import "./lifecycle-admin.css";
function humanize(value:string){return value.replaceAll("-"," ").replace(/\b\w/g,(character)=>character.toUpperCase());}
function formatDate(value?:string){if(!value)return"—";const date=new Date(value);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(date);}
function cloneDraft(draft:LifecycleAutomationConfiguration[]){return draft.map((item)=>({...item,selectedConditionIds:[...item.selectedConditionIds]}));}
function issueText(issues:LifecycleConfigurationValidationIssue[],automationId:LifecycleAutomationId){return issues.filter((issue)=>issue.automationId===automationId).map((issue)=>issue.message);}
export function LifecycleConfigurationPage({organizationId,canManage,initialTab="Configuration"}:{organizationId:string;canManage:boolean;initialTab?:"Configuration"|"Run history"}){
 const[workspace,setWorkspace]=useState<LifecycleWorkspaceSnapshot|null>(null);const[draft,setDraft]=useState<LifecycleAutomationConfiguration[]>([]);const[tab,setTab]=useState(initialTab);const[state,setState]=useState<"loading"|"ready"|"error">("loading");const[commandState,setCommandState]=useState<"idle"|"saving"|"publishing">("idle");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[refreshKey,setRefreshKey]=useState(0);const scopeRef=useRef(organizationId);scopeRef.current=organizationId;
 useEffect(()=>{let active=true;setState("loading");setCommandState("idle");setError("");setNotice("");void lifecycleAutomationPort.getWorkspace(organizationId).then((result)=>{if(!active||scopeRef.current!==organizationId)return;setWorkspace(result);setDraft(cloneDraft(result.draft));setState("ready");}).catch((cause:unknown)=>{if(!active||scopeRef.current!==organizationId)return;setWorkspace(null);setDraft([]);setError(cause instanceof Error?cause.message:"Lifecycle configuration could not be loaded.");setState("error");});return()=>{active=false;};},[organizationId,refreshKey]);
 const issues=useMemo(()=>workspace?validateLifecycleDraft(workspace.catalog,workspace.templates,draft):[],[draft,workspace]);const dirty=canManage&&workspace?JSON.stringify(draft)!==JSON.stringify(workspace.draft):false;const busy=commandState!=="idle";const displayedConfigurations=canManage?draft:(workspace?.published?.automations??workspace?.defaults??[]);
 const updateAutomation=(automationId:LifecycleAutomationId,update:(configuration:LifecycleAutomationConfiguration)=>LifecycleAutomationConfiguration)=>{if(!canManage||busy)return;setNotice("");setDraft((current)=>current.map((configuration)=>configuration.automationId===automationId?update(configuration):configuration));};
 const saveDraft=async()=>{if(!workspace||!canManage||busy||issues.length)return;const commandOrganizationId=organizationId;setCommandState("saving");setError("");setNotice("");try{const saved=await lifecycleAutomationPort.saveDraft(commandOrganizationId,cloneDraft(draft),workspace.draftRevision);if(scopeRef.current!==commandOrganizationId)return;setWorkspace(saved);setDraft(cloneDraft(saved.draft));setNotice("Draft saved after the authoritative command returned successfully.");}catch(cause){if(scopeRef.current!==commandOrganizationId)return;setError(cause instanceof Error?cause.message:"The lifecycle draft was not saved.");}finally{if(scopeRef.current===commandOrganizationId)setCommandState("idle");}};
 const publishDraft=async()=>{if(!workspace||!canManage||busy||dirty||issues.length)return;const commandOrganizationId=organizationId;setCommandState("publishing");setError("");setNotice("");try{const published=await lifecycleAutomationPort.publishDraft(commandOrganizationId,workspace.draftRevision);if(scopeRef.current!==commandOrganizationId)return;setWorkspace(published);setDraft(cloneDraft(published.draft));setNotice(`Published lifecycle configuration version ${published.published?.version??"unknown"} after the authoritative command succeeded.`);}catch(cause){if(scopeRef.current!==commandOrganizationId)return;setError(cause instanceof Error?cause.message:"The lifecycle draft was not published.");}finally{if(scopeRef.current===commandOrganizationId)setCommandState("idle");}};
 return <><PageHeader eyebrow="Customer lifecycle" title="Acquisition lifecycle" description="Configure the approved Release 2 acquisition catalog with bounded timing, fixed safety predicates, published email templates, and human-readable run explanations. This is not a workflow canvas or unrestricted segment builder."/>
 {!canManage?<Card className="lifecycle-readonly-notice"><Badge>Read only</Badge><p>You can inspect the active published configuration, or inherited defaults when no version is published, plus run explanations. This membership does not have lifecycle.manage; trusted backend authorization must enforce the same restriction.</p></Card>:null}
 {state==="loading"?<Card><LoadingState label="Loading lifecycle configuration…"/></Card>:null}{state==="error"?<Card><ErrorState message={error}/><div className="lifecycle-command-row"><Button onClick={()=>setRefreshKey((value)=>value+1)}>Retry</Button></div></Card>:null}
 {state==="ready"&&workspace?<><div className="lifecycle-status-grid"><Card><span className="muted">Catalog</span><strong>{workspace.catalogVersion}</strong><small>{workspace.catalog.length} approved automations</small></Card><Card><span className="muted">{canManage?"Draft revision":"Configuration view"}</span><strong>{canManage?workspace.draftRevision:workspace.published?`Published v${workspace.published.version}`:"Inherited defaults"}</strong><small>{canManage?(dirty?"Unsaved local changes":"Matches saved draft"):"Unpublished draft changes are not shown"}</small></Card><Card><span className="muted">Published</span><strong>{workspace.published?`v${workspace.published.version}`:"Not published"}</strong><small>{workspace.published?formatDate(workspace.published.publishedAt):"Defaults remain previewable without outbound activation"}</small></Card><Card><span className="muted">Outbound campaigns</span><strong>{humanize(workspace.outboundActivation.status)}</strong><small>{workspace.outboundActivation.explanation}</small></Card></div><Tabs items={["Configuration","Run history"]} active={tab} onSelect={(item)=>setTab(item as "Configuration"|"Run history")}/>
 {tab==="Configuration"?<>{workspace.catalog.map((entry)=>{const configuration=displayedConfigurations.find((item)=>item.automationId===entry.id);const inherited=workspace.defaults.find((item)=>item.automationId===entry.id);if(!configuration||!inherited)return null;const provenance=lifecycleConfigurationProvenance(configuration,workspace.defaults);const template=workspace.templates.find((candidate)=>candidate.templateId===configuration.templateId);const entryIssues=canManage?issueText(issues,entry.id):[];return <Card className="lifecycle-automation-card" key={entry.id}><div className="lifecycle-card-heading"><div><div className="lifecycle-inline-badges"><Badge tone="accent">{entry.id}</Badge><Badge tone={configuration.enabled?"positive":"neutral"}>{configuration.enabled?"Enabled":"Disabled"}</Badge><Badge>{provenance==="nurture-default"?"Nurture default":"Organization override"}</Badge></div><h2>{entry.label}</h2><p>{entry.intent}</p></div><label className="lifecycle-enable"><span>Enabled</span><input type="checkbox" checked={configuration.enabled} disabled={!canManage||busy} onChange={(event)=>updateAutomation(entry.id,(current)=>({...current,enabled:event.currentTarget.checked}))}/></label></div>
 <div className="lifecycle-config-grid"><label>Timing<Select value={configuration.timingId} disabled={!canManage||busy} onChange={(event)=>updateAutomation(entry.id,(current)=>({...current,timingId:event.currentTarget.value}))}>{entry.timingChoices.map((choice)=><option key={choice.id} value={choice.id}>{choice.label}</option>)}</Select><small>{entry.timingChoices.find((choice)=>choice.id===configuration.timingId)?.description}</small></label><label>Published email template<Select value={configuration.templateId} disabled={!canManage||busy} onChange={(event)=>updateAutomation(entry.id,(current)=>({...current,templateId:event.currentTarget.value}))}>{workspace.templates.filter((candidate)=>candidate.purpose===entry.messagePurpose).map((candidate)=><option key={candidate.templateId} value={candidate.templateId}>{candidate.label} · v{candidate.publishedVersion}</option>)}</Select><small>{template?.readinessExplanation??"Template readiness is unavailable."}</small></label></div>
 <fieldset className="lifecycle-conditions" disabled={!canManage||busy}><legend>Approved conditions rechecked before dispatch</legend>{entry.conditionChoices.map((condition)=>{const checked=configuration.selectedConditionIds.includes(condition.id);return <label key={condition.id}><input type="checkbox" checked={checked} disabled={!canManage||busy||condition.required} onChange={(event)=>updateAutomation(entry.id,(current)=>({...current,selectedConditionIds:event.currentTarget.checked?Array.from(new Set([...current.selectedConditionIds,condition.id])):current.selectedConditionIds.filter((conditionId)=>conditionId!==condition.id)}))}/><span><strong>{condition.label}{condition.required?" · Required":""}</strong><small>{condition.description}</small></span></label>;})}</fieldset>
 <div className="lifecycle-preview"><p className="eyebrow">Human-readable preview</p><ul>{automationPreviewLines(entry,configuration,workspace.templates).map((line)=><li key={line}>{line}</li>)}</ul></div>{entryIssues.length?<div className="lifecycle-validation" role="alert">{entryIssues.map((message)=><p key={message}>{message}</p>)}</div>:null}<div className="lifecycle-card-footer"><small>Trigger and execution are owned by the trusted event/runtime tracks. Track A edits only approved configuration.</small><Button className="button-secondary" disabled={!canManage||busy||provenance==="nurture-default"} onClick={()=>updateAutomation(entry.id,()=>({...inherited,selectedConditionIds:[...inherited.selectedConditionIds]}))}>Reset to inherited</Button></div></Card>;})}
 {error?<ErrorState message={error}/>:null}{notice?<div className="lifecycle-success" role="status">{notice}</div>:null}{canManage?<Card className="lifecycle-command-bar"><div><strong>Draft and publication are separate.</strong><p>Saving does not change active runs. Publishing creates a version for the runtime to pin; current consent, suppression, pause, customer existence, and commercial state still override queued permission.</p></div><div className="lifecycle-command-row"><Button className="button-secondary" disabled={busy||!dirty||issues.length>0} onClick={()=>void saveDraft()}>{commandState==="saving"?"Saving…":"Save draft"}</Button><Button disabled={busy||dirty||issues.length>0} onClick={()=>void publishDraft()}>{commandState==="publishing"?"Publishing…":"Publish saved draft"}</Button></div></Card>:null}</>:<Card><div className="lifecycle-card-heading"><div><p className="eyebrow">Run explanations</p><h2>Scheduled, held, suppressed, cancelled, and completed work</h2><p>These are read summaries from the acquisition runtime. Track A does not infer delivery or success from the browser.</p></div><Badge>{workspace.runHistory.length} records</Badge></div>{workspace.runHistory.length?<div className="lifecycle-run-list">{workspace.runHistory.map((run)=><article key={run.runId}><div className="lifecycle-run-marker" aria-hidden="true"/><div><div className="lifecycle-card-heading"><div><strong>{run.automationLabel}</strong><p><Link href={`/org/${organizationId}/admin/customers/${run.customerId}`}>{run.customerId}</Link> · {run.automationId}</p></div><Badge tone={["suppressed","cancelled","failed","held","unknown-outcome"].includes(run.status)?"warning":run.status==="completed"?"positive":"accent"}>{humanize(run.status)}</Badge></div><p>{run.reason}</p><small>Pinned {run.pinnedVersion} · Updated {formatDate(run.updatedAt)}{run.nextActionAt?` · Next ${formatDate(run.nextActionAt)}`:""}</small></div></article>)}</div>:<EmptyState title="No run history" description="No authorized acquisition-run explanations were returned for this organization."/>}</Card>}</>:null}</>;
}
