import { describe, expect, it } from "vitest";
import { lifecycleDraftToConfigurationExtension, validateLifecycleDraft } from "./contracts";
import { createLifecycleWorkspaceFixture } from "./fixtures";
import { DemoLifecycleAutomationPort } from "./port";

describe("Release 2 Track A lifecycle configuration",()=>{
  it("accepts only the fixed catalog and required safety predicates",()=>{ const workspace=createLifecycleWorkspaceFixture("org-one"); const invalid=workspace.draft.map((item)=>({...item,selectedConditionIds:[...item.selectedConditionIds]})); invalid[0]!.selectedConditionIds=[]; const issues=validateLifecycleDraft(workspace.catalog,workspace.templates,invalid); expect(issues.some((issue)=>issue.automationId==="R2-WELCOME"&&issue.field==="conditions")).toBe(true); });
  it("saves a draft without altering the published version, then publishes an immutable snapshot",async()=>{ const port=new DemoLifecycleAutomationPort(); const initial=await port.getWorkspace("org-one"); expect(initial.published).toBeNull(); const edited=initial.draft.map((item)=>item.automationId==="R2-WELCOME"?{...item,enabled:true}:item); const saved=await port.saveDraft("org-one",edited,initial.draftRevision); expect(saved.draft.find((item)=>item.automationId==="R2-WELCOME")?.enabled).toBe(true); expect(saved.published).toBeNull(); const published=await port.publishDraft("org-one",saved.draftRevision); expect(published.published?.version).toBe(1); const editedAgain=published.draft.map((item)=>item.automationId==="R2-WELCOME"?{...item,timingId:"after-15-min"}:item); const savedAgain=await port.saveDraft("org-one",editedAgain,published.draftRevision); expect(savedAgain.published?.automations.find((item)=>item.automationId==="R2-WELCOME")?.timingId).toBe(published.published?.automations.find((item)=>item.automationId==="R2-WELCOME")?.timingId); });
  it("keeps organization drafts isolated and rejects stale commands",async()=>{ const port=new DemoLifecycleAutomationPort(); const first=await port.getWorkspace("org-one"); const second=await port.getWorkspace("org-two"); const edited=first.draft.map((item)=>item.automationId==="R2-LEAD"?{...item,enabled:true}:item); const saved=await port.saveDraft("org-one",edited,first.draftRevision); expect((await port.getWorkspace("org-two")).draft).toEqual(second.draft); await expect(port.saveDraft("org-one",saved.draft,first.draftRevision)).rejects.toThrow(/changed since it was loaded/i); });
  it("serializes lifecycle configuration into only Track A's opaque extension key",()=>{ const workspace=createLifecycleWorkspaceFixture("org-one"); const serialized=lifecycleDraftToConfigurationExtension(workspace.draft); expect(serialized.extensionKey).toBe("lifecycle:acquisition"); expect(serialized.extension.namespace).toBe("nurture.lifecycle.acquisition"); expect(serialized.extension.payload.catalogVersion).toBe("r2-acquisition-v1"); });
});
